### ISSUE TITLE
Add  weather functionality to the extension.

### ISSUE THREAD

**Issue by praveen-me** [praveen-me/special-fortnight-chrome-extension#1]
You can refer  https://openweathermap.org/api API for making this.

**Comment by silvia-odwyer** [comment]
I'm interested in completing this for you. However, I'm just wondering:  How would the user's location be determined? Would the user enter their own city in a text field?

**Comment by praveen-me** [comment]
Ya, we can ask the city name. And then process according to the query. And also when they enter the city it will be stored in Local Storage.

**Comment by praveen-me** [comment]
> I'm interested in completing this for you. However, I'm just wondering: How would the user's location be determined? Would the user enter their own city in a text field?
Ya, we can ask the city name. And then process according to the query. And also when they enter the city it will be stored in Local Storage.

**Comment by praveen-me** [comment]
> I'm interested in completing this for you. However, I'm just wondering: How would the user's location be determined? Would the user enter their own city in a text field?

Ya, @silvia-odwyer  we can ask the city name. And then process according to the query. And also when they enter the city it will be stored in Local Storage.

**Comment by silvia-odwyer** [comment]
Perfect, I'll get started on this for you. I'm going to put the function to check the weather in `main.js`, if that's okay with you. 

Also let me know where you want the weather tile to be placed in the actual layout of the extension's layout. I was thinking to place it underneath the To Do List, but you can always move this according to your desires later on anyway.

**Comment by praveen-me** [comment]
If you can make another branch do that otherwise ya, I am ok you can put your function in main.js.
I think to put weather section in the top-most left corner.  What do you think about that?

**Comment by silvia-odwyer** [comment]
That sounds perfect! I'll get started on this then :D

**Comment by eznix86** [comment]
the proposition I offer is: make a Get request on 'http://maps.googleapis.com/maps/api/geocode/json?latlng=' + HERELATITUDE + ',' + HERELONGITUDE + '&sensor=true' to get location
